### ISSUE TITLE
Filter module issue

### ISSUE THREAD

**Issue by oganm** [hackseq/tara-cyc-hs18#5]
At least one filter module option (TYPE = 'GOV') leaves a single sample with no coordinates, leaving the map empty. make sure not to do that in the presumed demo tomorrow and learn what it actually is and if there are other conditions like that

**Comment by oganm** [comment]
This part also needs virus vs bacteria filtering

**Comment by laijasmine** [comment]
also the map table is cutting off the rest of the columns (starting at pwyorder)
